wandb/helm-charts

.github/workflows/lint-test.yaml, charts/wandb/Chart.yaml, charts/wandb/ci/basic-values.yaml, charts/wandb/templates/_helpers.tpl, charts/wandb/templates/configmap.yaml, charts/wandb/templates/deployment.yaml, charts/wandb/templates/ingress.yaml, charts/wandb/templates/mysql.yaml, charts/wandb/templates/secrets.yaml, charts/wandb/templates/tests/test-connection.yaml, charts/wandb/values.yaml
This implements some more functionality in the core helm chart.
=> Updates for dev tools and mysql

charts/launch-agent/Chart.yaml
Github workflow should now successfully release packages
=> bump agent version to unbork ci

.github/CODEOWNERS, README.md, charts/wandb/Chart.yaml, charts/wandb/README.md
Amendments made to the wandb chart README, and added CODEOWNERS file.
=> feat: Update README, add CODEOWNERS

charts/wandb/Chart.yaml, charts/wandb/templates/deployment.yaml
=> fix: Fix bucket queue env var

charts/launch-agent/Chart.yaml, charts/launch-agent/templates/configmap.yaml, charts/launch-agent/templates/deployment.yaml, charts/launch-agent/templates/rbac.yaml, charts/launch-agent/templates/secret.yaml
Also fixes: https://wandb.atlassian.net/browse/WB-16022
=> Launch: Support multiple instances in the same namespace

charts/operator-wandb/Chart.yaml, charts/operator-wandb/values.yaml
Disabling install of the bundled OTEL collector for now.
=> disable otel install

charts/operator-wandb/Chart.lock, charts/operator-wandb/Chart.yaml, charts/operator-wandb/charts/app/templates/deployment.yaml
- chore: Remove statd host port if otel is not enabled
- empty
=> chore: Remove statd host port if otel is not enabled

charts/wandb/Chart.yaml, charts/wandb/README.md, charts/wandb/templates/deployment.yaml, charts/wandb/templates/secrets.yaml, charts/wandb/values.yaml
feat: Add support to ldap custom certs
=> feat: Add support to ldap custom certs

charts/launch-agent/Chart.yaml, charts/launch-agent/values.yaml
bumping launch agent version to 0.16.3 post release
=> chore(launch): bump agent version to 0.16.3

charts/wandb/Chart.yaml
fix: Bump wandb and chart version
=> fix: Bump wandb and chart version

charts/operator-wandb/Chart.yaml, charts/operator-wandb/charts/app/templates/deployment.yaml, charts/operator-wandb/charts/flat-run-fields-updater/Chart.yaml, charts/operator-wandb/charts/flat-run-fields-updater/templates/deployment.yaml
Some light cleanup of variables that are not needed in certain deployments
=> chore(backend): clean up runs v2 env variables

charts/operator-wandb/Chart.yaml, charts/operator-wandb/templates/ingress.yaml
should be a pure revert of this: https://github.com/wandb/helm-charts/commit/e5c061f07a3257ff3c120a8e3e70c322a8a44164
=> feat: Option to create cert for gce

charts/operator-wandb/Chart.yaml, charts/operator-wandb/charts/parquet/templates/cron.yaml
just copying whats in the parquet deployment
=> fix: Mount redis cert to parquet cron job

charts/operator-wandb/Chart.yaml, charts/operator-wandb/charts/app/templates/deployment.yaml, charts/operator-wandb/charts/flat-run-fields-updater/templates/deployment.yaml, charts/operator-wandb/templates/_kafka.tpl, charts/operator-wandb/values.yaml
Add an environment variable for being able to change the number of partitions in kafka
=> chore(dev): make kafka partitions configurable

charts/operator-wandb/Chart.yaml, charts/operator-wandb/charts/flat-run-fields-updater/templates/deployment.yaml
Fix this issue
```
json: cannot unmarshal number into Go struct field EnvVar.spec.template.spec.containers.env.value of type string\nhelm.sh/helm/v3/pkg/kube.(*Client).Update\n\t/go/pkg/mod/helm.sh/helm/v3@v3.12.0-dev.1/pkg/kube/client.go:441\nhelm.sh/helm/v3/pkg/action.(*Upgrade).releasingUpgrade\n\t/go/pkg/mod/helm.sh/helm/v3@v3.12.0-dev.1/pkg/action/upgrade.go:378\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1598","stacktrace":"github.com/wandb/operator/controllers.(*WeightsAndBiasesReconciler).Reconcile\n\t/workspace/controllers/weightsandbiases_controller.go:189\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.1/pkg/internal/controller/controller.go:122\nsigs.k8s.io/controller-runtime/pkg/in …
```
=> chore(dev): fix frfu num partitions

charts/operator-wandb/Chart.yaml, charts/operator-wandb/charts/flat-run-fields-updater/templates/deployment.yaml, charts/operator-wandb/values.yaml
Tested it this time
```
jessicaxiang@Jessica-Xiang-RCPYPN70YT helm-charts % helm upgrade wandb ./charts/operator-wandb/ --reuse-values
Release "wandb" has been upgraded. Happy Helming!
NAME: wandb
LAST DEPLOYED: Wed Jul 10 16:53:11 2024
NAMESPACE: default
STATUS: deployed
REVISION: 204
TEST SUITE: None
jessicaxiang@Jessica-Xiang-RCPYPN70YT helm-charts %
```
=> chore(dev): make frfu value a string

charts/operator-wandb/Chart.yaml, charts/operator-wandb/charts/weave/templates/deployment.yaml, charts/operator-wandb/charts/weave/values.yaml
https://wandb.atlassian.net/browse/WB-19627
=> fix: HPA could not scale weave 

charts/operator-wandb/Chart.yaml, charts/operator-wandb/charts/weave-trace/templates/deployment.yaml, charts/operator-wandb/charts/weave-trace/templates/serviceaccount.yaml, charts/operator-wandb/charts/weave-trace/values.yaml, charts/operator-wandb/charts/weave/templates/deployment.yaml, charts/operator-wandb/charts/weave/templates/serviceaccount.yaml, charts/operator-wandb/charts/weave/values.yaml
Add an SA for weave-trace deployment
=> fix: Add an SA for weave-trace deployment

charts/operator-wandb/Chart.yaml, charts/operator-wandb/charts/yace/values.yaml
Correct syntax for yace search tags
=> fix: Correct syntax for yace search tags

charts/operator-wandb/Chart.yaml, charts/operator-wandb/charts/weave/templates/deployment.yaml
=> fix: Revert private WANDB_BASE_URL for weave

charts/operator-wandb/Chart.yaml, charts/operator-wandb/charts/parquet/templates/deployment.yaml, charts/operator-wandb/charts/parquet/values.yaml
Allow for configurable replicas for parquet
=> chore: allow for parquet replicas

charts/operator-wandb/Chart.yaml, charts/operator-wandb/charts/console/templates/role.yaml
The console needs to be able to create a secret the first time it comes up in a cluster.
=> fix: Console Password Creation

charts/operator/Chart.yaml, charts/operator/templates/deployment.yaml, charts/operator/values.yaml
=> fix: Fix extraEnv reference

charts/operator-wandb/Chart.yaml, charts/operator-wandb/values.yaml
=> chore(dev): update kafka storage

charts/operator-wandb/charts/app/templates/_deployment.tpl, charts/operator-wandb/charts/flat-run-fields-updater/templates/deployment.yaml, charts/operator-wandb/charts/otel/Chart.lock, charts/operator-wandb/charts/parquet/templates/cron.yaml, charts/operator-wandb/charts/parquet/templates/deployment.yaml, charts/operator-wandb/charts/prometheus/charts/mysql-exporter/templates/deployment.yaml, charts/operator-wandb/charts/prometheus/charts/redis-exporter/templates/deployment.yaml, charts/operator-wandb/templates/_redis.tpl, charts/operator-wandb/templates/redis.yaml, charts/operator-wandb/values.yaml
Reimplement https://github.com/wandb/helm-charts/pull/223, as the only way I could figure out exactly what I wanted was to do it.
=> feat: Support reading redis password from a user supplied secret

charts/operator-wandb/Chart.yaml, charts/operator-wandb/charts/app/templates/_deployment.tpl
Fixing a mistake from https://github.com/wandb/helm-charts/pull/248
=> chore(artifacts): convert gc env vars to strings

charts/operator-wandb/Chart.lock, charts/operator-wandb/Chart.yaml, charts/operator-wandb/charts/app/templates/_deployment.tpl, charts/operator-wandb/charts/filestream/.helmignore, charts/operator-wandb/charts/filestream/Chart.yaml, charts/operator-wandb/charts/filestream/templates/_helpers.tpl, charts/operator-wandb/charts/filestream/templates/deployment.yaml, charts/operator-wandb/charts/filestream/templates/hpa.yaml, charts/operator-wandb/charts/filestream/templates/serviceaccount.yaml, charts/operator-wandb/charts/filestream/values.yaml, charts/operator-wandb/charts/flat-run-fields-updater/templates/deployment.yaml, charts/operator-wandb/charts/flat-run-fields-updater/values.yaml, charts/operator-wandb/values.yaml
=> feat: WIP - Chart for filestream service

charts/operator-wandb/Chart.yaml, charts/operator-wandb/charts/app/templates/_deployment.tpl, charts/operator-wandb/charts/app/templates/_helpers.tpl, charts/operator-wandb/charts/executor/templates/_helpers.tpl, charts/operator-wandb/charts/executor/templates/deployment.yaml, charts/operator-wandb/charts/filestream/templates/_helpers.tpl, charts/operator-wandb/charts/filestream/templates/deployment.yaml, charts/operator-wandb/charts/filestream/values.yaml, charts/operator-wandb/charts/flat-run-fields-updater/templates/_helpers.tpl, charts/operator-wandb/charts/flat-run-fields-updater/templates/deployment.yaml, charts/operator-wandb/charts/flat-run-fields-updater/values.yaml, charts/operator-wandb/charts/parquet/templates/_helpers.tpl, charts/operator-wandb/charts/parquet/templates/deployment.yaml, charts/operator-wandb/values.yaml
Moving around some values to simplify the interface between our terraform and the chart, and to make more clear what values are needed by the charts that were previously being passed as global envs.
=> fix: Reorganize the way values are passed

charts/operator-wandb/Chart.lock, charts/operator-wandb/Chart.yaml, charts/operator-wandb/templates/_ingress.tpl, charts/operator-wandb/values.yaml, charts/wandb-base/Chart.yaml, charts/wandb-base/templates/service.yaml
=> fix: API service annotations

charts/operator-wandb/Chart.yaml, charts/operator-wandb/charts/app/templates/deployment.yaml, charts/operator-wandb/charts/app/templates/service.yaml, charts/operator-wandb/templates/gorilla.yaml
=> fix: Anaconda for sweeps

charts/operator-wandb/Chart.yaml, charts/operator-wandb/charts/app/templates/service.yaml, charts/operator-wandb/charts/console/templates/service.yaml, charts/operator-wandb/values.yaml
=> feat: Add `gcpSecurityPolicy`

.github/CODEOWNERS, charts/operator-wandb/Chart.yaml, charts/operator-wandb/charts/app/templates/service.yaml, charts/operator-wandb/charts/console/templates/service.yaml, charts/operator-wandb/charts/weave-trace/templates/service.yaml
also fixed an error were I missed removing a createBackendConfig flag and adds some custom healthCheck path.
=> fix: Update weave-trace gcp related settings
