wandb/helm-charts

- charts/launch-agent/Chart.yaml
- charts/launch-agent/templates/deployment.yaml
Exposing the name of the service account that the wandb launch agent is using in an environment variable so that the agent can read it and use the same service account when it creates kaniko pods.
> Add service account name as environment variable in agent pod

- charts/launch-agent/Chart.yaml
- charts/launch-agent/README.md
- charts/launch-agent/templates/deployment.yaml
- charts/launch-agent/templates/secret.yaml
- charts/launch-agent/templates/volcano.yaml
- charts/launch-agent/values.yaml
This PR introduces a `gitCreds` variable which can be set to the literal contents of a `.git-credentials` file. The chart puts this into a secret and mounts it in the home directory of the agent container, if `gitCreds` is specified by the user. It will also mount
```
[credentials]
helper = store
```
in `~/.gitconfig` to prevent git from prompting for a username and password and instead going straight to the cred store we have mounted.
I also added a table that documents all the variables to the readme.
> add variable for mounting git credentials

- charts/launch-agent/templates/volcano.yaml
In some environments, like GKE, you need to manually add a resource quota to allow system-critical pods to run in the namespaces created by volcano.
> fix: volcano resource quota

- charts/launch-agent/Chart.yaml
- charts/launch-agent/templates/volcano.yaml
Volcano's default queue was being created in a weird state that prevented jobs from being created successfully. Just updated the vendored bits to the latest manifest from their repo and it worked. This is a short term solution until we can find a way good way to include volcano in our deployments.
> fix volcano broken queue state

- charts/launch-agent/Chart.yaml
- charts/launch-agent/templates/volcano.yaml
when I fixed the volcano deployment I copied their manifest again and didn't add back the templating that makes the volcano install conditional on the volcano helm variable.
> make the volcano variable work again

- .github/CODEOWNERS
Prior to this PR the `CODEOWNERS` file has launch codeowners specified before the default setting. [These docs](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners#:~:text=%23%20These%20owners%20will%20be%20the%20default%20owners%20for%20everything%20in%0A%23%20the%20repo.%20Unless%20a%20later%20match%20takes%20precedence%2C%0A%23%20%40global%2Downer1%20and%20%40global%2Downer2%20will%20be%20requested%20for%0A%23%20review%20when%20someone%20opens%20a%20pull%20request.%0A*%20%20%20%20%20%20%20%40global%2Downer1%20%40global%2Downer2) seem to suggest that we need the default to be specified before the more specific codeowner assignments.
> enable launch-agent codeowners

- charts/launch-agent/Chart.yaml
- charts/launch-agent/values.yaml
Now that we have versioning for our agent releases we should be pinning the agent image in a chart version to a permanently unique tag, which for the agent repo means sdk version.
> pin agent image to sdk release 0.16.0

- charts/launch-agent/Chart.yaml
- charts/launch-agent/templates/deployment.yaml
- charts/launch-agent/templates/secret.yaml
This is a companion PR to [this SDK PR](https://github.com/wandb/wandb/pull/6722). Instead of only creating the `wandb-api-key` secret in the agent's namespace, create one in every namespace used by the agent. This way, secrets are created when the agent is spun up instead of at job runtime. This also allows the helm deployment to manage cleanup of the secrets when the agent is spun down.
Since we allow multiple agents on the same namespace, and different agents may want to use different secrets, these separate secrets are denoted by the agent's `.Release.Name`, which is passed to the agent through the `WANDB_RELEASE_NAME` env var.
> feat: Create api key secret in all namespaces

- charts/operator-wandb/Chart.yaml
- charts/operator-wandb/charts/parquet/templates/deployment.yaml
I've thrown in what seemed like sensible defaults to me - please let me know if we want to edit these or template these out.
> chore: readiness and liveness probes for parquet

- charts/operator-wandb/Chart.yaml
- charts/operator-wandb/templates/ingress.yaml
- charts/operator-wandb/values.yaml
Example istio networking:
```
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
labels:
app.kubernetes.io/managed-by: Helm
name: wandb-vs
namespace: wandb-operator
spec:
gateways:
- wandb-operator/wandb-gw
hosts:
- '*'
http:
- match:
- uri:
prefix: /console
port: 31005
route:
- destination:
host: wandb-console.wandb-operator.svc.cluster.local
port:
number: 8082
- match:
- uri:
prefix: /
port: 31005
route:
- destination:
host: wandb-app.wandb-operator.svc.cluster.local
port:
number: 8080 
```
Eventually we could also technically template this out with an `istio.install: true`
> feat: Allow ingress to be disabled for customers using Istio 

- charts/operator-wandb/Chart.yaml
- charts/operator-wandb/charts/weave/templates/_helpers.tpl
- charts/operator-wandb/charts/weave/templates/deployment.yaml
- charts/operator-wandb/charts/weave/values.yaml
weave was using host url for auth
this would fail if the url was ip allow listed
make the request to app.fullName(wandb-app) 
[dd error ](https://app.datadoghq.com/apm/trace/7825151400505903724?colorBy=service&env=managed-install&graphType=flamegraph&shouldShowLegend=true&sort=time&spanID=5329251616330542402&spanViewType=errors&timeHint=1713267779966.6892&view=spans)
screenshot showing the proper url in the env and that you can curl it (qa-aws)
> chore(weave): Use app fullname for weave auth

- charts/operator-wandb/Chart.yaml
- charts/operator-wandb/templates/ingress.yaml
```
➜ helm upgrade wandb . --reuse-values                                                     
Error: UPGRADE FAILED: template: operator-wandb/templates/ingress.yaml:89:14: executing "operator-wandb/templates/ingress.yaml" at <.Values.ingress.secondary.create>: nil pointer evaluating interface {}.create
```
> fix: Check if secondary is nil

- charts/launch-agent/Chart.yaml
- charts/launch-agent/templates/deployment.yaml
- charts/launch-agent/values.yaml
This templates affinity into the agent's deployment spec so users can manage affinities similarly to tolerations and nodeSelectors
> feat: add affinity template into agent

- charts/operator-wandb/Chart.yaml
- charts/operator-wandb/charts/weave/templates/deployment.yaml
This var allows weave to use a more direct url when making pod to pod request while maintaining the normal wandb base url for frontend requests
This fixes an issues where wandb pod ip allowlisting blocked the weave pod from making requests to the public ip
> chore(weave): add weave public url

- charts/operator-wandb/Chart.yaml
- charts/operator-wandb/charts/flat-run-fields-updater/templates/deployment.yaml
It appears this is a requirement for Google environments: https://weightsandbiases.slack.com/archives/C06GPQCSFS5/p1720566416252899
> chore(dev): redis certificate for flat run fields updater

- charts/operator-wandb/Chart.yaml
- charts/operator-wandb/charts/flat-run-fields-updater/templates/deployment.yaml
Seeing 
```
"cannot patch \"wandb-flat-run-fields-updater\" with kind Deployment: Deployment.apps \"wandb-flat-run-fields-updater\" is invalid: spec.template.spec.containers[0].volumeMounts[0].name: Not found: \"wandb-flat-run-fields-updater-redis-ca\""
```
Noticing all the other deployments seem to have this additional block.
> chore(dev): fix flat run fields updater redis volume

- charts/operator-wandb/Chart.yaml
- charts/operator-wandb/charts/console/templates/service.yaml
- charts/operator-wandb/values.yaml
AWS Load Balancer controller will use annotations on the service to configure health checks on the ALB target groups that relate to it otherwise it will default to `/` 
https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.2/guide/ingress/annotations/#health-check
- Add a cloudProvider value to globals
- When cloudProvider is AWS add relevant annotations to the Service for console
> fix: add hc annotation to the console service in AWS clusters

- charts/operator-wandb/Chart.yaml
- charts/operator-wandb/charts/app/templates/deployment.yaml
- charts/operator-wandb/charts/flat-run-fields-updater/templates/deployment.yaml
- charts/operator-wandb/values.yaml
Realized that my initial attempted fix here: https://github.com/wandb/helm-charts/pull/168 did not update both deployments (app and frfu). Something still seemed to be broken on the latest chart version. 
Manually applied this change
```
jessicaxiang@Jessica-Xiang-RCPYPN70YT helm-charts % helm upgrade wandb ./charts/operator-wandb/ --reuse-values
Release "wandb" has been upgraded. Happy Helming!
NAME: wandb
LAST DEPLOYED: Tue Jul 16 09:36:52 2024
NAMESPACE: default
STATUS: deployed
REVISION: 352
TEST SUITE: None
jessicaxiang@Jessica-Xiang-RCPYPN70YT helm-charts %
```
Things seem to be working again: https://qa-aws.wandb.io/console/settings/advanced
> chore(dev): run updates shadow partitions

- charts/operator-wandb/Chart.yaml
- charts/operator-wandb/charts/flat-run-fields-updater/templates/deployment.yaml
Seeing errors in datadog when spinning up FRFU deployment on AWS: https://app.datadoghq.com/logs?query=customer-ns%3Awandb-qa-aws%20container_name%3Aflat-run-fields-updater%20&agg_m=count&agg_m_source=base&agg_t=count&cols=host%2Cservice&event=AgAAAZC8gckgnFx-TQAAAAAAAAAYAAAAAEFaQzhnZHQ1QUFDRUtGT0VBSzNhWEFBTwAAACQAAAAAMDE5MGJjODEtZmJlYS00ZGViLWE2ZmEtM2UyZDY3ODAyYWMy&fromUser=true&messageDisplay=inline&refresh_mode=sliding&storage=hot&stream_sort=service%2Casc&viz=stream&from_ts=1721148577565&to_ts=1721149477565&live=true
```
!!! The AWS_REGION environment variable is required when specifying BUCKET. Please restart the container with AWS_REGION set to the region containing your bucket.
```
Believe this is the fix. Tested application
```
jessicaxiang@Jessica-Xiang-RCPYPN70YT helm-charts % …
```
> chore(dev): add AWS_REGION to frfu deployment

- charts/operator-wandb/Chart.yaml
- charts/operator-wandb/charts/app/templates/_helpers.tpl
- charts/operator-wandb/charts/flat-run-fields-updater/templates/_helpers.tpl
- charts/operator-wandb/charts/parquet/templates/_helpers.tpl
This PR enables support for subpaths in GCP https://github.com/wandb/terraform-google-wandb/pull/145/files
Testing:
Manually deployed with https://github.com/wandb/helm-charts/blob/levinandrew/byob-subpath/charts/operator-wandb/local-development.md
- when the new `bucket_path` in the above terraform, was NOT specified, when I ssh'd to the wandb-app pod, I saw 
```
wandb@wandb-app-65d8cb96-m7jb5:~$ env | grep -i bucket
BUCKET=gs://andrew-levin-gcp-intense-goblin
```
- when the new `bucket_path` was specified as `"nested/path/test", I saw
```
wandb@wandb-app-7cbb475896-79266:~$ env | grep -i nested
BUCKET=gs://andrew-levin-gcp-intense-goblin/nested/path/test
"store": "gs://andrew-levin-gcp-intense-goblin/nested/path/test",
OVERFLOW_BUCKET_ADDR=gs://andrew-levin-gcp-intense-goblin/nested/path …
```
> feat(backend): enable subpath in GCP

- charts/operator-wandb/Chart.yaml
- charts/operator-wandb/charts/app/templates/serviceaccount.yaml
- charts/operator-wandb/charts/app/values.yaml
- charts/operator-wandb/charts/console/templates/deployment.yaml
- charts/operator-wandb/charts/console/templates/serviceaccount.yaml
- charts/operator-wandb/charts/console/values.yaml
- charts/operator-wandb/charts/parquet/templates/deployment.yaml
- charts/operator-wandb/charts/parquet/templates/serviceaccount.yaml
- charts/operator-wandb/charts/parquet/values.yaml
Normalize the service account create logic for all wandb applications
https://github.com/wandb/terraform-google-wandb/pull/151
To support changes in terraform-google-wandb version 5.0 with `enable_workload_identity`
> fix: Normalize the service account create logic for all wandb applications

- charts/operator-wandb/Chart.yaml
- charts/operator-wandb/charts/weave/templates/deployment.yaml
reverts the change 
https://github.com/wandb/helm-charts/pull/159
to maintain back compat with 56 and below
> chore(weave): Revert weave cache import update

- charts/operator-wandb/Chart.yaml
- charts/operator-wandb/values.yaml
We can't re-partition without downtime so best to start higher than we think we'll need. I don't think any of our customers would actually struggle with 1. We can set this for different customers with environment variables but setting it here streamlines the deployment process.
> chore(dev): increase default kafka partitions for frfu

- charts/operator-wandb/Chart.yaml
- charts/operator-wandb/charts/weave-trace/templates/deployment.yaml
> fix: Clean up DD_* env vars in weave-trace deployment

- charts/operator-wandb/Chart.yaml
- charts/operator-wandb/charts/app/templates/deployment.yaml
This may fix the injection of custom CA to the wandb-app if the intention is to make the certs a global config.
If the idea is to make it local to `app` only I can move it to the correct chart.
```
helm dependency build ./charts/operator-wandb
Hang tight while we grab the latest from your chart repositories...
...Successfully got an update from the "metrics-server" chart repository
...Successfully got an update from the "descheduler" chart repository
...Successfully got an update from the "ceph-csi" chart repository
...Successfully got an update from the "ingress-nginx" chart repository
...Successfully got an update from the "cert-manager-webhook-pdns" chart repository
...Successfully got an update from the "hashicorp" chart repository
...Successfully got an update from the …
```
> fix: Fix CACert value reference

- charts/operator-wandb/Chart.yaml
- charts/operator-wandb/charts/app/templates/_helpers.tpl
- charts/operator-wandb/charts/app/templates/deployment.yaml
- charts/operator-wandb/charts/flat-run-fields-updater/templates/_helpers.tpl
- charts/operator-wandb/charts/flat-run-fields-updater/templates/deployment.yaml
- charts/operator-wandb/charts/parquet/templates/_helpers.tpl
- charts/operator-wandb/charts/parquet/templates/cron.yaml
- charts/operator-wandb/charts/parquet/templates/deployment.yaml
- charts/operator-wandb/templates/bucket.yaml
- charts/operator-wandb/values.yaml
There are some scenarios where we want to provide setting for the storage bucket that are overwritten via console ui and this change should allow the console to know the source of the configuration
> feat: Differentiate between bucket settings provided as default and set explicitly by the user for wandb managed installs

- charts/operator-wandb/Chart.yaml
- charts/operator-wandb/charts/parquet/templates/cron.yaml
- charts/operator-wandb/charts/parquet/templates/deployment.yaml
- charts/operator-wandb/charts/parquet/templates/service.yaml
The K8s Service for Parquet will also pickup the backfill job pods and add them as endpoints, this is not desirable.
> fix: Parquet service pod selector is not specific enough

- charts/operator-wandb/Chart.yaml
- charts/operator-wandb/charts/weave/templates/deployment.yaml
un reverts https://github.com/wandb/helm-charts/pull/185
which reverted https://github.com/wandb/helm-charts/pull/161
We reverted the initial change because we had a weave error in artifacts, that while we triaged it was safer to revert, now we need this change back in.
> fix: unrevert private WANDB_BASE_URL for weave

- .gitignore
- charts/operator-wandb/Chart.yaml
- charts/operator-wandb/charts/app/templates/_deployment.tpl
- charts/operator-wandb/charts/app/templates/_helpers.tpl
- charts/operator-wandb/charts/app/templates/deployment.yaml
- charts/operator-wandb/charts/app/templates/hpa.yaml
- charts/operator-wandb/charts/app/values.yaml
- charts/operator-wandb/local-development.md
- charts/operator-wandb/templates/_helpers.tpl
**Case A**: Default case. `.Values.glueSingleton.enabled = false` then
```yaml
app:
glueSingleton:
enabled: false
autoscaling: 
hpa:
enabled: false
maxReplicas: 10
minReplicas: 5
image:
repository: wandb/local-dev
tag: 0.60.0-pre-hpa.0
```
1. The app deployment is created with `GLUE_ENABLED = true` which is a *no-op*
2. The app pod will **not** set `ONLY_SERVICE`
3. The glue deployment not created
**This is a noop** for existing deployments. 
---
**Case B**: This is the case where we want to run the glue container in addition  to the app container. `.Values.glueSingleton.enabled = true` then:
```yaml
app:
glueSingleton:
enabled: true
autoscaling:
hpa:
enabled: true
maxReplicas: 10
minReplicas: 5
image:
repository: wandb/local-dev
tag: 0.60.0-pre-hpa.0
```
1. The app deployment is created …
> feat: Init HPA workaround

- charts/operator-wandb/Chart.yaml
- charts/operator-wandb/charts/app/templates/_deployment.tpl
- charts/operator-wandb/charts/flat-run-fields-updater/templates/deployment.yaml
Set replication factor to be 3 for kafka to have higher availability during leader elections. We have three brokers so 3 is the highest that we can go.
> Increase kafka replication factor

- charts/operator-wandb/Chart.yaml
- charts/operator-wandb/values.yaml
Enable jmx metrics from kafka instances. Daniel got this working for Google QA: https://deploy.wandb.ai/v2/admin/channels/8524aba0-2e34-42e7-a359-d451af023304
> chore(dev): enable kafka jmx metrics

- charts/operator-wandb/Chart.lock
- charts/operator-wandb/Chart.yaml
- charts/operator-wandb/charts/app/templates/_deployment.tpl
- charts/operator-wandb/charts/app/templates/configmap.yaml
- charts/operator-wandb/charts/parquet/templates/configmap.yaml
- charts/operator-wandb/charts/parquet/templates/deployment.yaml
- charts/operator-wandb/values.yaml
Add support to pull the list of CA Certs from configMaps (W&B App)
Create configmap
```
apiVersion: v1
kind: ConfigMap
metadata:
name: custom-ca-certs
data:
ca-cert1.crt: |
-----BEGIN CERTIFICATE-----
...
-----END CERTIFICATE-----
ca-cert2.crt: |
-----BEGIN CERTIFICATE-----
...
-----END CERTIFICATE-----
```
values.yaml 
configMapName: "custom-ca-certs"
> feat: Add support to pull CA Certs from configMap

- charts/operator-wandb/Chart.yaml
- charts/operator-wandb/charts/app/templates/_deployment.tpl
- charts/operator-wandb/charts/parquet/templates/cron.yaml
- charts/operator-wandb/charts/parquet/templates/deployment.yaml
The default [GOGC](https://pkg.go.dev/runtime#hdr-Environment_Variables) behavior is not great for many workloads, and it is especially bad for Parquet, because it is based entirely on the ratio between memory that survived the previous GC event and the amount of freshly allocated objects. By setting `GOMEMLIMIT`, we'll only trigger GC events when we're close to pod's limits.
> chore: set GOMEMLIMIT in app, parquet

- charts/operator-wandb/Chart.yaml
- charts/operator-wandb/charts/console/values.yaml
- charts/operator-wandb/values.yaml
technically not required, but including for documentation.
> feat: Option to pass through reference to iam identity to console

- charts/operator-wandb/Chart.yaml
- charts/operator-wandb/charts/executor/templates/_helpers.tpl
- charts/operator-wandb/charts/executor/templates/deployment.yaml
The executor pod needs to be able to write to runs v2 (flat run fields) for moving runs, etc. 
Make sure it has the proper environment variables to know which queue to write to.
> fix: enable flat run field updates in executor pod

- charts/operator-wandb/Chart.yaml
- charts/operator-wandb/templates/_bucket.tpl
This solves an issue where there is a trailing `/` in the bucket if path is not set. 
Before:
```yaml
- name: BUCKET
value: "gs://$(BUCKET_NAME)/$(BUCKET_PATH)"
```
After
```yaml
- name: BUCKET
value: "gs://$(BUCKET_NAME)"
```
The problem is that then the bucket will be
Before
```bash
BUCKET=gs://wandb-qa-local-whole-crow/
```
After
```bash
BUCKET=gs://wandb-qa-local-whole-crow
```
Which can lead to issues with the application.
> fix: Bucket postfix trailing slash

- charts/operator-wandb/Chart.yaml
- charts/operator-wandb/templates/gorilla.yaml
- charts/operator-wandb/values.yaml
Fix a templating issue where it was producing the raw string of 
```bash
"redis://$(REDIS_HOST):$(REDIS_PORT)"
```
in the configmap which is invalid.
> fix: Task Queue Templating

- charts/operator-wandb/Chart.lock
- charts/operator-wandb/Chart.yaml
- charts/operator-wandb/templates/_kafka.tpl
- charts/operator-wandb/templates/_mysql.tpl
- charts/operator-wandb/templates/gorilla.yaml
- charts/operator-wandb/values.yaml
- charts/wandb-base/Chart.yaml
- charts/wandb-base/templates/service.yaml
- charts/wandb-base/values.yaml
We are planning to remove the conditional for the backend on  `{{- if .Values.global.createGCPLoadBalancerBackend }}` just need time to validate. 
We can also make the spec conditional for the backend config in the future.
ref INFRA-269
> feat: Backend config, mysql connection string, hpa

- charts/operator-wandb/Chart.yaml
- charts/operator-wandb/templates/_bucket.tpl
ref INFRA-344
Essentially a user's configured bucket would inherit values from defaultBucket, really this should just be one or the other, if a bucket is set as determined by name then use all of the settings from bucket, otherwise use all of the settings from defaultBucket.
> fix: Switch between default bucket and bucket based on name

- charts/operator-wandb/Chart.yaml
- charts/operator-wandb/charts/app/templates/deployment.yaml
currently we always pass an env var to the app pod that causes the glue process to try to bind to port 8080, which is already in use by nginx. it would be nice to avoid that
> fix: pass a port number to glue that doesn't collide with nginx

- charts/operator-wandb/Chart.yaml
- charts/operator-wandb/values.yaml
Api pod uses the same defaults as the app pod.
> fix: Use the same defaults

- charts/operator-wandb/Chart.lock
- charts/operator-wandb/Chart.yaml
- charts/operator-wandb/values.yaml
This is the existing behaviour of the app pod.
> fix: Migrations don't block gorilla startup

- charts/operator-wandb/Chart.yaml
- charts/operator-wandb/charts/app/templates/deployment.yaml
- charts/operator-wandb/charts/parquet/templates/deployment.yaml
The ident for the annotations block under `spec` is 4 instead it should be 8. This is causing the annotations to be reconciled and reverted when user sets it directly in deployment.yaml.
> fix: Fix indent for annotations block under `spec`

- charts/wandb-base/Chart.yaml
- charts/wandb-base/templates/service.yaml
- charts/wandb-base/values.yaml
ref INFRA-392
follow up changes for `console`/`app` required since they don't yet use `wandb-base`.
> feat: Add gcp Security Policy to wandb-base

- charts/launch-agent/Chart.yaml
- charts/launch-agent/templates/deployment.yaml
- charts/launch-agent/values.yaml
https://wandb.atlassian.net/browse/WB-26209
Heads up, this PR merges into the `dom/public-queue` branch which has the RBAC necessary for the launch agent to create resources for the vllm service.
This PR adds an `oidc` configuration to the chart so we can set the launch agent up as an approved launch agent (federated identity). When enabled, the `WANDB_IDENTITY_TOKEN_FILE` env var will be set to the projected service account token volume.
> chore(launch): Add projected sa volume capabilities
